# Generated by Django 4.2.5 on 2023-09-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('created_at',)},
        ),
    ]
